### ISSUE TITLE
Error when trying to install the package from MyGet nuget repo 

### ISSUE THREAD

**Issue by SepiaGroup** [JimBobSquarePants/ImageSharp#102]
PM> Install-Package ImageSharp -Version 1.0.0-alpha2-00052
Install-Package : The V2 feed at 'https://www.myget.org/F/imagesharp/symbols/FindPackagesById()?id='ImageSharp'' returned an 
unexpected status code '404 Not Found'.

At line:1 char:1
+ Install-Package ImageSharp -Version 1.0.0-alpha2-00052
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], FatalProtocolException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

Also cannot build the solution either because i VS cannot find the source, same error

**Comment by SepiaGroup** [comment]
i resolved this the issue i was having in building the source.

**Comment by JimBobSquarePants** [comment]
>i resolved this the issue i was having in building the source.

@SepiaGroup That does really resolve the issue does it? Also, don't do that. Now you have a dependency issue. 

Your issue is that you are using the incorrect url to pull from. Where did you find that? 

Even following the url you provided by clicking on it throws a 404 so you should have been able to see that the url is incorrect.

The correct url for the package feed is:

**V3**
https://www.myget.org/F/imagesharp/api/v3/index.json

**V2**
https://www.myget.org/F/imagesharp/

You can find these by following the link in the readme file. 

P.S. **I cannot stress this enough**. Please do not delete the issue template. Doing so should have been a red flag to you submitting the issue as you didn't do the prerequisite research.
