### ISSUE TITLE
error resizing image

### ISSUE THREAD

**Issue by niksan321** [JimBobSquarePants/ImageSharp#132]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have an error while resizing this image:
![nakladki_na_porogi_ladya_mazda_6_32](https://cloud.githubusercontent.com/assets/2101530/23914799/1d96ba34-08f8-11e7-83af-006dbca07a69.jpg)

Unable to cast object of type 'System.Byte[]' to type 'System.Byte'

### Steps to Reproduce

in params:
name = nakladki_na_porogi_ladya_mazda_6_32.jpg
pathIn = c:\in\
pathOut = c:\out\
maxWidth = 250
maxHeight = 190

        public void GenerateOptimizedJpg(string name, string pathIn, string pathOut, int maxWidth, int maxHeight, int quality = 60)
        {
            var imgIn = $"{pathIn}{name}";
            var imgOut = $"{pathOut}{Path.GetFileNameWithoutExtension(name)}.jpg";
            var photoBytes = File.ReadAllBytes(imgIn);

            var resizeOptions = new ResizeOptions
            {
                Mode = ResizeMode.Max,
                Size = new Size(maxWidth, maxHeight),
                Position = AnchorPosition.Center,
            };

            using (var inStream = new MemoryStream(photoBytes))
            using (var output = File.OpenWrite(imgOut))
            {
                var options = new JpegEncoderOptions { Quality = quality };
                var image = new Image(inStream);
                image.BackgroundColor(Color.White)
                    .Resize(resizeOptions)
                    .SaveAsJpeg(output, options);
            }
        }

### System Configuration

- ImageSharp version: 
    "ImageSharp.Drawing": "1.0.0-alpha2-00158",
    "ImageSharp.Formats.Bmp": "1.0.0-alpha2-00158",
    "ImageSharp.Formats.Gif": "1.0.0-alpha2-00158",
    "ImageSharp.Formats.Jpeg": "1.0.0-alpha2-00158",
    "ImageSharp.Formats.Png": "1.0.0-alpha2-00154",
    "ImageSharp.Processing": "1.0.0-alpha2-00146"

- .NET Framework version: netcoreapp1.1

**Comment by blackcity** [comment]
Exiftools output:
<pre>
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : Adobe Photoshop CS4 Windows
Modify Date                     : 2014:03:28 16:44:10
White Point                     : 0 0
Primary Chromaticities          : 0 0 0 0 0 0
Y Cb Cr Coefficients            : 0 0 0
Y Cb Cr Positioning             : Unknown (0)
Reference Black White           : 0 0 0 0 0 0
Exposure Time                   : 0
F Number                        : 0
Exposure Program                : Not Defined
ISO                             : 0, 0
Exif Version                    : 1220
Compressed Bits Per Pixel       : 0
Shutter Speed Value             : 1
Aperture Value                  : 1.0
Brightness Value                : 0
Exposure Compensation           : 0
Max Aperture Value              : 1.0
Subject Distance                : 0 m
Metering Mode                   : Unknown
Light Source                    : Unknown
Flash                           : No Flash
Focal Length                    : 0.0 mm
<strong>Flashpix Version                : </strong>
Color Space                     : sRGB
Exif Image Width                : 850
Exif Image Height               : 638
Focal Plane X Resolution        : 0
Focal Plane Y Resolution        : 0
Focal Plane Resolution Unit     : Unknown (0)
Exposure Index                  : 0
Sensing Method                  : Unknown (0)
File Source                     : Unknown (0)
Scene Type                      : Unknown (0)
Image Width                     : 220
Image Height                    : 165
Encoding Process                : Progressive DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 220x165
Megapixels                      : 0.036
Shutter Speed                   : 0
Focal Length                    : 0.0 mm
</pre>

Seems the FlashpixVersion tag causes the issue since it has some invalid props.

@JimBobSquarePants In our solutions we're remove these messy tags. But if the library wants to handle it, it should set the number of components to the length of the byte array:
https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/MetaData/Profiles/Exif/ExifReader.cs#L322

**Comment by JimBobSquarePants** [comment]
Thanks for the detail @niksan321 and for the extra info @blackcity 👍 

@dlemstra tagging you here as this will affect Magick.Net also

**Comment by tocsoft** [comment]
fixed in #168
