### ISSUE TITLE
Drawing crisp single pixel width text

### ISSUE THREAD

**Issue by KLuuKer** [JimBobSquarePants/ImageSharp#138]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
With the old System.Drawing i am using ZXing.Net to make it render a image like this
![crisp-text](https://cloud.githubusercontent.com/assets/12729178/24005529/8f3b60fa-0a69-11e7-995f-08aa55101011.jpg)

i tried allot of varations with the following (enable\disable AA, font sizes, pen width's, even dpi)
```c#
var top = height - 4;
var font = new Font(FontCollection.SystemFonts.Find("Arial"), 10f, FontStyle.Regular);
var pen = new Pen(Color.Black, 1);
img.DrawText(orderTicket.Code, font, pen, new System.Numerics.Vector2(50, top), new TextGraphicsOptions(false));
```
but i cant get that nice crispy single pixel wide text (no need to concern yourself with the barcode that works just fine)

![fat](https://cloud.githubusercontent.com/assets/12729178/24005925/954b1480-0a6a-11e7-9970-a29fb2deddaa.jpg)
![no-aa](https://cloud.githubusercontent.com/assets/12729178/24005926/96826b82-0a6a-11e7-8f52-2aa762328f74.jpg)
![no-aa-hor-dpi](https://cloud.githubusercontent.com/assets/12729178/24005795/450b6718-0a6a-11e7-91eb-d2e19161c449.jpg)

maybe @tocsoft can help with this

### System Configuration
- ImageSharp version: 1.0.0-alpha3-00005
- ImageSharp Drawing version: 1.0.0-alpha3-00005
- Environment (Operating system, version and so on): windows 10 x64
- .NET Framework version: net461 (but if this works i'm switching to netcoreapp1.1)

**Comment by tocsoft** [comment]
don't use a pen instead use a brush or color instead 

try 
``` c#
var top = height - 4;
var font = new Font(FontCollection.SystemFonts.Find("Arial"), 10f, FontStyle.Regular);
var brush = new SolidBrush(Color.Black);
img.DrawText(orderTicket.Code, font, brush, new System.Numerics.Vector2(50, top), new TextGraphicsOptions(false));
```

Basically the rule of thumb is a `Pen` is sued for outlining/drawing lines which may or may not have a pattern where as a `Brush` is used to fill it in.

**Comment by tocsoft** [comment]
BTW its awesome to see this usage of it the library. 👍

**Comment by KLuuKer** [comment]
hmmm that solidbrush definitely helped 

AA on
![solidbrush](https://cloud.githubusercontent.com/assets/12729178/24007716/bf431d3c-0a6f-11e7-833a-d50865b81225.jpg)
AA off
![solidbrush-x](https://cloud.githubusercontent.com/assets/12729178/24007717/bf4544d6-0a6f-11e7-8297-78b2b5e3987f.jpg)

it's just not that nice crispy pixel perfect aligned text that System.Drawing makes
![drawing](https://cloud.githubusercontent.com/assets/12729178/24005529/8f3b60fa-0a69-11e7-995f-08aa55101011.jpg)

**Comment by tocsoft** [comment]
The Font library doesn't currently perform pixel grid aligning which should help knock the glyphs over to better match the pixel layout. I've added an issue over there to track that. SixLabors/Fonts#19 pixel grid aligning should be part of the problem.

Additionally I've never tested trying to get a font to render at a single pixel width, i'll have to have a play to see if there anything quick I can do to improve the renderer for you.

You could try seeing if offsetting the text by half a pixel helps i.e. draw the text at `new System.Numerics.Vector2(50.5, top)` instead of 50. (should do the same thing as the pixel grid aligning but manually, might help.)

I'll have a play around with trying to draw the text at this size and see if I can make it "just work" for you.

**Comment by KLuuKer** [comment]
I tried the manual offset alignment but it only helped a tiny amount
![manual-offset](https://cloud.githubusercontent.com/assets/12729178/24016875/1484ace8-0a8e-11e7-8096-a3dc8510db9b.jpg)

If i would have to fix it like this i would have to align each and every single letter\number... 😢 
So if you are able to perform pixel grid alignment that would be great!

https://en.wikipedia.org/wiki/ClearType that is the word that really describes this problem

**Comment by tocsoft** [comment]
@KLuuKer  try "1.0.0-alpha4-00021" for both ImageSharp & ImageSharp.Drawing. 

Its still not as good as System.Drawing because I'm still not doing font hinting and grid fitting but it should improve general font rendering making small glyphs render better. 

You will want to render using anti-aliasing for the closest match.

**Comment by KLuuKer** [comment]
@tocsoft o wow this is so much better now, thank you very much for the quick (and huge) improvement in the rendering
![new-pixel-align-aa](https://cloud.githubusercontent.com/assets/12729178/24076957/5da6852a-0c3e-11e7-81c8-23898bfa8f35.jpg)

even with aa turned off it also looks better then before
![new-pixel-align-no-aa](https://cloud.githubusercontent.com/assets/12729178/24076958/5da88ca8-0c3e-11e7-8f27-cb1c4a393ae4.jpg)

thank you very much for doing this, i can finally start setting fire to net461 😄 (it's a big app so it might take some time to burn)

**Comment by JimBobSquarePants** [comment]
Great work @tocsoft ! 💯

**Comment by jez9999** [comment]
@KLuuKer All the same, it still doesn't reproduce that pixel-perfect aligned text produced by System.Drawing, does it?  I totally know what you mean by that, it makes Arial look just perfect.

@tocsoft Was this ever fixed with ImageSharp?  I've been experimenting with the latest (1.0.0-beta15) and as this issue above says, antialiased looks alright (though not the same as the "pixel perfect" look, and unantialiased is atrocious:

![renderings](https://user-images.githubusercontent.com/793830/197769880-8498e790-773d-4886-b062-21a115d880f2.png)

**Comment by JimBobSquarePants** [comment]
Try the latest MyGet build with hinting enabled. I’ve just done a ton of work there.

**Comment by jez9999** [comment]
Wasn't intended as a negative, more as a factual description of how difficult it is to actually read. :-)

Sorry, I don't know what you mean by the MyGet?

**Comment by Kiritsu** [comment]
Hey @jez9999, have you found a good configuration to make it render as good as possible?

I've tried lots of different fonts (including "pixel-like" fonts), playing with the Brushes/Pens and Hinting. Probably a me-problem but I couldn't manage to play with aliasing's options.

I couldn't get something clearer than this: 
![image](https://user-images.githubusercontent.com/22667054/203568485-48173d04-d453-4959-9e30-2b4d80f757f9.png)

If you zoom it you can see different shade of black: 
![image](https://user-images.githubusercontent.com/22667054/203568589-a5f9b2e4-0812-4ebf-8d75-8b01a9cee8dc.png)

My wish would be to limit that amount of shade, even if it lowers the general quality, but I couldn't manage to get something better than this. 

It is an issue to me right now because I have something that then attempts to replace the color around the text (sadly without any tolerance) which then makes the final rendering a bit weird.

**Comment by JimBobSquarePants** [comment]
>Probably a me-problem but I couldn't manage to play with aliasing's options.
What do you mean by this? Are you using the [1.0.0-beta19](https://www.nuget.org/packages/SixLabors.Fonts/1.0.0-beta19). The hinter has been fixed and works the same as Freetype's one now. 

>It is an issue to me right now because I have something that then attempts to replace the color around the text (sadly without any tolerance) which then makes the final rendering a bit weird.

That's more an issue than the font rendering IMO. You always need tolerance when doing color replacement. ImageSharp.Drawing has a `RecolorBrush` to do this. 

Though of course the smart thing to do would be to draw the text onto the correct colored background in the first place.

**Comment by AnastasiiaShta** [comment]
Hello
I faced a problem:
At a font size of 20, the inscription is displayed quite well
![Capture](https://user-images.githubusercontent.com/122535966/212071571-64c02a05-49a3-4fa6-879a-5f4ae1a8a28d.PNG)

When I reduce the font size 10, the resolution degrades
![image](https://user-images.githubusercontent.com/122535966/212071945-2562609b-75bd-49bc-a411-7b6190fcddcc.png)

Font size  5
![image](https://user-images.githubusercontent.com/122535966/212072273-414a3f8f-c728-46ec-bf3b-6c7cc8839675.png)

Приклад коду:
`          var font = family.CreateFont(10, FontStyle.Regular);

image.Mutate(x=>x.DrawText(
                                       text, 
                                       font, 
                                       new SolidBrush(Color.Black), 
                                       new PointF(rectangle.X , rectangle.Y)));
`
I save the photo in jpg format. When I use png the situation is much better, but as the font size decreases, the resolution still degrades a lot. I need to save it exactly in jpg format. Maybe you can help me with this.

Я використовую  1.0.0-beta19 версію бібліотеки

**Comment by AnastasiiaShta** [comment]
Hello
I faced a problem:
I save the photo in jpg format. When I use png the situation is much better, but as the font size decreases, the resolution still degrades a lot. I need to save it exactly in jpg format. Maybe you can help me with this.

Font size 20
![image](https://user-images.githubusercontent.com/122535966/212078860-90455dc8-5b6c-4835-9b9a-afbc246c6df1.png)

Font size 10
![image](https://user-images.githubusercontent.com/122535966/212078747-f7fa95a6-db0d-451f-8a0d-7c9449a9be4a.png)

Font size 5
![image](https://user-images.githubusercontent.com/122535966/212078584-2335be53-06a5-4849-aeb8-9caeb1ece4f0.png)

`var font = family.CreateFont(10, FontStyle.Regular);
image.Mutate(x=>x.DrawText(
                                       text, 
                                       font, 
                                       new SolidBrush(Color.Black), 
                                       new PointF(rectangle.X , rectangle.Y)));`


I'm using version 1.0.0-beta19

**Comment by JimBobSquarePants** [comment]
@AnastasiiaShta This is a closed issue. Please open a new discussion or issue with the relevant details.

**Comment by AnastasiiaShta** [comment]
> 
I'm new here, sorry.
I opened a new one here.
https://github.com/SixLabors/ImageSharp/discussions/2318
Thank you.

**Comment by AnastasiiaShta** [comment]
> @AnastasiiaShta This is a closed issue. Please open a new discussion or issue in the correct repository with the relevant details.

I'm new here, sorry.
I opened a new one here.
https://github.com/SixLabors/ImageSharp/discussions/2318
Thank you.
