### ISSUE TITLE
Gone from MyGet?

### ISSUE THREAD

**Issue by kierenj** [JimBobSquarePants/ImageSharp#145]
Hi - it looks like most of the packages are gone from MyGet.  The symbol packages are still there, but not for example Processing or the individual formats?

(I can manually create a link to https://www.myget.org/feed/imagesharp/package/nuget/ImageSharp.Formats.Bmp and see it, but it doesn't appear at https://www.myget.org/gallery/imagesharp when searching, and NuGet - dotnet restore - can't find it)

**Comment by tocsoft** [comment]
The reason they are gone is because you are not supposed to be using them anymore, we rolled the formats and processors back down into the core `ImageSharp` package.

All you need to do is reference  `ImageSharp` and if you want the drawing APIs the optional  `ImageSharp.Drawing`.

PS. The reason the symbols are still there is because we've failed to find the magic piece of myget's UI to hide them,

**Comment by JimBobSquarePants** [comment]
Hi @kierenj 

Here's a shot description of the functionality of the two remaining packages. They cover all the prior ones and more.

- **ImageSharp**
  - Contains the Image classes, Colors, Primitives, Configuration, and other core functionality.
  - The IImageFormat interface, Jpeg, Png, Bmp, and Gif formats.
  - Transform methods like Resize, Crop, Skew, Rotate - Anything that alters the dimensions of the image.
  - Non-transform methods like Gaussian Blur, Pixelate, Edge Detection - Anything that maintains the original image dimensions.

- **ImageSharp.Drawing**
  - Brushes and various drawing algorithms, including drawing images.
  - Various vector drawing methods for drawing paths, polygons etc.
  - Text drawing.
