### ISSUE TITLE
Using ImageSharp with raw array of bytes (rgb8, rgba8, bgr8, etc...)

### ISSUE THREAD

**Issue by andrecarlucci** [JimBobSquarePants/ImageSharp#176]
Hi guys,

I'm trying to use this library with a raw array of bytes (RGB8, 24bits per pixel). Is that possible?

More info about these formats here: https://github.com/IntelRealSense/librealsense/blob/master/doc/supported_video_formats.pdf

and

https://github.com/IntelRealSense/librealsense/blob/5c24f5eb3a35b300ff16f98124a044a8a5936db6/src/image.cpp

Thanks!

**Comment by JimBobSquarePants** [comment]
Hi @andrecarlucci,

Theoretically yes. 

Here's a [collection of all the pixel formats](https://github.com/JimBobSquarePants/ImageSharp/tree/7eac3f59f8781778af8c67b42bce2d7658d09472/src/ImageSharp/Colors/PackedPixel) we support out of the box. It's the same as XNA and MonoGame covering the multitude of types used by graphics cards in gaming. 

Adding your own type would be a case of implementing the [`IPixel`](https://github.com/JimBobSquarePants/ImageSharp/blob/7eac3f59f8781778af8c67b42bce2d7658d09472/src/ImageSharp/Colors/PackedPixel/IPixel.cs) interface. 

`Image<TColor>` itself supports [creating instances](https://github.com/JimBobSquarePants/ImageSharp/blob/7eac3f59f8781778af8c67b42bce2d7658d09472/src/ImageSharp/Image/Image%7BTColor%7D.cs#L49) without decoding an image format so you would be able to new up an instance and map your byte array to the image `TColor[]`

This might all be a bit clunky to use though so I would be very interested in seeing your use case to ensure that our API exposes enough useful public methods to allow raw pixel manipulation from byte streams. Our emphasis so far has most definitely been on decoding/encoding from image formats. 

Cheers

James

P.S We normally use [Gitter](https://gitter.im/ImageSharp/General?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for questions rather than the issue tracker.
