### ISSUE TITLE
Image.SaveAsPng + others are missing System.IO.Compression

### ISSUE THREAD

**Issue by makotech222** [JimBobSquarePants/ImageSharp#184]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am running the latest version of ImageSharp
- [ x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to execute the method, Image.SaveAsPng(FileStream fs), I get an exception saying:

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.IO.Compression, Version=4.1.1.0

SaveAsJpg does the same.

### Steps to Reproduce
Created new Console Application on .Net 4.6.1, got the latest nuget package from myget. The nuget downloads System.IO.Compression Version 4.3, when 4.1.1.0 is required. SaveAsBmp seems to work, though.

### System Configuration
Windows 10 x64, Visual Studio 2017 Community. .Net 4.6.1 project.
Imagesharp alpha6 00065

As an aside, I ran into a huge amount of build issues when trying to get this to work with .Net standard projects. 1.1, 1.3, 1.6, didn't matter. Wouldn't build when the library using imagesharp was added as a reference. Had to switch to 4.6.1.

Another aside, SaveAsBmp seems it should have a method that uses the BmpEncoderOptions instance, like all the other SaveAs methods do.

**Comment by JimBobSquarePants** [comment]
Hi @makotech222 

Thanks for providing so much information. We really appreciate it when people fill in the form properly.

It took me a while but I managed to replicate your issue and provide a fix. There's some [oddities](https://github.com/dotnet/corefx/issues/16206) in the way NetStandard 1.6.1 works with references but that should be fixed with NetStandard 2.0.0 

I've uploaded some test projects I created to demonstrate the issue, created a new alpha to fix it and will describe here what I discovered.

In the zip file you will find three separate projects.

1. **Test.ISharp** - A **NetCore 1.1** console application directly referencing **1.0.0-alpha6-00065**. _This works with no issues_.
2. **Test.ISharp.Classic461** - A classic **.Net 4.6.1** console application directly referencing **1.0.0-alpha6-00065**. _This works with no issues_.
3. **Test.ISharp.Multiple** A **NetStandard 1.3** class library referencing **1.0.0-alpha6-00066** with two consuming console projects. The first **NetCore 1.1** the second **.Net 4.6.1**. _Everything built correctly but at runtime errors were thrown. This was where the fun started!_

When testing **Test.ISharp.Multiple** against **1.0.0-alpha6-00065** the NetCore project worked first time without any problems. 

The **.NET 4.6.1** project however first complained that it could not find the ImageSharp binary. **I had to directly reference it in both the class library and consuming console application**.

Rerunning the application then threw your error. I fixed this by adding a direct reference to `System.IO.Compression v4.3.0` to ImageSharp. If you update your reference to **1.0.0-alpha6-00066** everthing should now JustWork™

Let me know if you have any further issues.

Cheers

James

[ImageSharp.Tests.zip](https://github.com/JimBobSquarePants/ImageSharp/files/945979/ImageSharp.Tests.zip)

**Comment by makotech222** [comment]
Didn't know if i should open a new issue for this, but Its the same issue but with System.Numerics.Vector library.

Set up is Create new .net standard 1.3 library project, add latest imagesharp via nuget. Then create new .Net 4.6.1 console app. Add the .net standard 1.3 project to the new console app solution, reference it in console app project, then call some functions that use Vector2 class. Get this exception:

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

**Comment by JimBobSquarePants** [comment]
I don't think that's related to us. We've already added Vectors as a dependency. Did you add ImageSharp as a dependency to the console app also?

Sounds like an assembly redirect issue.

**Comment by makotech222** [comment]
No I didn't add it as a dependency to the console app, I don't think i need to? My library should contain all that is needed for ImageSharp, which shouldn't really be a part of my main application, especially if I'm using it to simply save an image.

Regardless, I added ImageSharp to my console app, and now I get:

System.TypeLoadException: 'Could not load type 'ImageSharp.Color' from assembly 'ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'

**Comment by JimBobSquarePants** [comment]
See my comment above.

>The .NET 4.6.1 project however first complained that it could not find the ImageSharp binary. I had to directly reference it in both the class library and consuming console application.

It seems to be a quirk with the current build system/standard combination. NetStandard 2.0.0 _should_ fix this.

Your new issue is due to https://github.com/JimBobSquarePants/ImageSharp/commit/cf62f7725dfff87a2c5468c1e3f94243d9e6adde

You'll need to get the latest in all projects, clean, then build again.

`Color` is now the more accurately named `Rgba32` (We're making sure we are inline with CoreClr naming conventions).

**Comment by makotech222** [comment]
Okay I'll give it a try soon. Yeah this .Net standard stuff... Can't wait until 2.0. Thanks again for the quick help.

**Comment by makotech222** [comment]
Okay confirmed, all is working as expected. Thanks for the quick help.

**Comment by JimBobSquarePants** [comment]
No worries as all. :smile:
