### ISSUE TITLE
Jpeg image not opening properly

### ISSUE THREAD

**Issue by pconfig** [JimBobSquarePants/ImageSharp#40]
I'm currently testing out this library to use in my future web app.

It works great for most images but some jpeg images don't open properly. Please check out the attached image. While I can open it in any program, ImageSharp returns 0 for height and width. (I hope Github does not alter the file in any way when uploading it)

![ph8261x1](https://cloud.githubusercontent.com/assets/24611078/21271540/acaa0dde-c3bb-11e6-8cd1-c90f4dec6a3d.jpg)

**Comment by JimBobSquarePants** [comment]
Hi @pconfig thanks for raising this and supplying the offending image. 

@dlemstra You had a quick look at this didn't you? Could you note your findings here please and I'll see if I can figure out how to get it working.

**Comment by dlemstra** [comment]
The issue is this line: https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/Formats/Jpg/JpegDecoderCore.cs#L1189. With 4 channels CMYK should be assumed (https://docs.oracle.com/javase/8/docs/api/javax/imageio/metadata/doc-files/jpeg_metadata.html). But it looks like only YCbCr is supported in the block inside the if. 

>If an Adobe APP14 marker segment is present, the colorspace is determined by consulting the transform flag. The transform flag takes one of three values:
2 - The image is encoded as YCCK (implicitly converted from CMYK on encoding).
1 - The image is encoded as YCbCr (implicitly converted from RGB on encoding).
0 - Unknown. 3-channel images are assumed to be RGB, 4-channel images are assumed to be CMYK

**Comment by JimBobSquarePants** [comment]
Ok... So what we originally thought was CMYK was actually YCCK... (I really do hate Jpeg and Adobe most of all.)

I've added the conversion method but without ICC profile support we're not going to be able to get the hue/saturation 100% correct.
