### ISSUE TITLE
Animated Gif encoding broken

### ISSUE THREAD

**Issue by jarroda** [JimBobSquarePants/ImageSharp#54]
I updated from 1.0.0-alpha-000075 to 1.0.0-alpha-000195, and noticed that animated gifs seem to now have issues.  I have done tests with a couple of images and see similar problems with both: black square artifacts on some frames of the gif.  

I have been reproducing the issue by simply resizing the image
```
new Image(inStream)
	.Resize(300,0)
	.Save(outStream);
```

My original test image:
![test-original](https://cloud.githubusercontent.com/assets/1840003/21365887/fd010ffe-c6bc-11e6-988c-e5f3d51f924a.gif)

Resized using 1.0.0-alpha-000195
![test-195](https://cloud.githubusercontent.com/assets/1840003/21365901/0e792820-c6bd-11e6-956a-4de29728cd59.gif)

Resized using 1.0.0-alpha-000075
![test-75](https://cloud.githubusercontent.com/assets/1840003/21365920/1c479680-c6bd-11e6-80e7-ad4016976a7f.gif)

**Comment by JimBobSquarePants** [comment]
Hi @jarroda 

I had a look and it's some optimizations to the gif decoder that appear to have broken the decoder. I have created a branch to work on the problem and have managed to revert the code to get a working code sample. I need to reapply the optimizations though one at a time in order to get a final working version so it may take a day or two. 

Cheers

James

**Comment by jarroda** [comment]
Fantastic.  Thanks.

**Comment by JimBobSquarePants** [comment]
Fixed now. Getting an odd result on a couple of frames when using the Octree Quantizer but the others work. Enjoy!
