### ISSUE TITLE
image (png) resize broken 

### ISSUE THREAD

**Issue by sanghv1987** [JimBobSquarePants/ImageSharp#76]
I have image (png) export from powerpoint
When i resize image broken 
![1](https://cloud.githubusercontent.com/assets/5163082/21875918/0e8ea068-d8b2-11e6-9e03-d55e3a41c68d.png)
![600_0_resize_1](https://cloud.githubusercontent.com/assets/5163082/21875928/1659ffa4-d8b2-11e6-98dc-67a9e2cd8145.png)
And this is my code

 ```
Image imageOrigin = ImageFromFile(originFile);
 ResizeMode mode = ResizeMode.Min;
using (FileStream output = File.OpenWrite(newFile))
            {

                ResizeOptions options = new ResizeOptions()
                {
                    Size = new Size(600, 0),
                    Mode = mode,
                };
                imageOrigin.Resize(options).Save(output);
            }
```
I using last code download from https://codeload.github.com/JimBobSquarePants/ImageSharp/zip/master (01/12/2017)
"version": "1.0.0-alpha1-*"

When i resize image (jpg)
![20170101085604](https://cloud.githubusercontent.com/assets/5163082/21876126/facf2cc2-d8b2-11e6-83ae-9d10305df0a7.jpg)

![715_0_resize_20170101085604](https://cloud.githubusercontent.com/assets/5163082/21876136/10dd348c-d8b3-11e6-93b6-9edeca4586f0.jpg)

reduce the contrast of the image

Please help me

**Comment by JimBobSquarePants** [comment]
Hi @sanghv1987 

Could you please read over the [Contribution Guidelines](https://github.com/JimBobSquarePants/ImageSharp/blob/master/contributing.md) highlighted to you when you raised this issue. It is imperative that you supply the version numbers as it makes it difficult for us to triage issues otherwise.

Also, please do not combine issues when raising them. 

Testing the images I can see that there is indeed a bug in our decoding of interlaced png files. However, I see no issue with the jpeg file. You have simply saved it at a lower quality (hint: Image has a Quality property).

Could you please supply those version numbers.

Thanks 

James

**Comment by JimBobSquarePants** [comment]
The png in question is an 8bit interlaced image with no filtering. I'm not sure what is going wrong yet. Looks like an offsetting calculation issue in the Adam7 deinterlacing though.

**Comment by sanghv1987** [comment]
I using last code download from https://codeload.github.com/JimBobSquarePants/ImageSharp/zip/master (01/12/2017).
 "version": "1.0.0-alpha1-*"

**Comment by sanghv1987** [comment]
My code test jpg Quality = 100

```
ImageSharp.Configuration.Default.AddImageFormat(new PngFormat());
            ImageSharp.Configuration.Default.AddImageFormat(new JpegFormat());
            ImageSharp.Configuration.Default.AddImageFormat(new GifFormat());

            string currentDirectory = Directory.GetCurrentDirectory();
            string path = Path.Combine(currentDirectory, "Images");
            string originFile = Path.Combine(path, "20170101085604.jpg");

            Image imageOrigin = ImageFromFile(originFile);
            IImageEncoder imageEncoder = new JpegEncoder()
            {
                Quality = 100,
                Subsample = JpegSubsample.Ratio444
            };
            string newFile = Path.Combine(path, "1280_0_20170101085604_1.jpg");
            using (FileStream output = File.OpenWrite(newFile))
            {
                ResizeOptions options = new ResizeOptions()
                {
                    Size = new Size(600, 0),
                    Mode = ResizeMode.Min,
                };
                imageOrigin.Resize(options).Save(output, imageEncoder);
            }
```
reduce the contrast of the image

![1280_0_20170101085604_1](https://cloud.githubusercontent.com/assets/5163082/21881449/ec91ea7c-d8d6-11e6-9dca-a4a0f17d628d.jpg)

**Comment by dlemstra** [comment]
You will "loose contrast" when you do that operation. First of all you are resizing an image and that will change the colors because multiple pixels are combined into a new pixel. And the format that you are using is JPG which is a lossy format and during conversions some of the information will be lost. You are getting the expected output. You could decide to call `.GaussianSharpen(0.5f)` on the image before saving i. That will "sharpen" it a bit but my advice would be keeping the image like it is now.

**Comment by sanghv1987** [comment]
Thank Dlemstra. I will keep the current image.

**Comment by dlemstra** [comment]
Closed by accident, we still need to fix the PNG stuff.

**Comment by JimBobSquarePants** [comment]
@sanghv1987 We've just pushed a fix for the png decoder. We've also done some work to improve jpeg output also. Please download the update from MyGet.

**Comment by sanghv1987** [comment]
@JimBobSquarePants Thank you. 
I checked again and the results were amazing

**Comment by JimBobSquarePants** [comment]
@dlemstra Was the genius here. Fixed it in a heartbeat after I spent hours looking at it.

**Comment by dlemstra** [comment]
It also took me hours 😄 but found it within 10 minutes after a full night's sleep.
