### ISSUE TITLE
JPEG XR support

### ISSUE THREAD

**Issue by dajbych** [JimBobSquarePants/ImageSharp#95]
I would welcome [JPEG XR](https://msdn.microsoft.com/en-US/windows/hardware/gg463400) support.

**Comment by JimBobSquarePants** [comment]
Please use the Gitter chatroom to discuss new features as described in the contribution guidlines. 

>Do you intend to add a new feature or change an existing one?
>Suggest your change in the ImageSharp Gitter Chat Room and start writing code

>Do not open an issue on GitHub until you have collected positive feedback about the change. GitHub issues are primarily intended for bug reports and fixes.

**Comment by springy76** [comment]
BTW: Source is available as [BSD lib](https://hdview.wordpress.com/2013/04/11/jpegxr-photoshop-plugin-and-source-code/)

"JPEG XR" aka "Windows Media Photo" aka "HD Photo" is one of the 6 built-in codecs when using WPF. I used it to create thousands of preview images due to its small size and very fast decoding speed.
